# wrangler.toml for Cloudflare Pages

name = "mediamanagerpro"
type = "javascript"
account_id = "535f3e26d64d48e5e93b795cb4f7a7e4"
workers_dev = true
compatibility_date = "2025-09-09"
main = "dist/index.js"

[build]
command = "npm run build"
directory = "dist"

[env.production]
# Specify any environment variables for production here, if needed

[env.dev]
# Specify any environment variables for dev environment here
